// components/resume/Education.vue
<template>
  <div class="flex-1">
    <div class="font-bold">{{ institute }}</div>
    <div class="text-gray-600">{{ location }}</div>
    <div class="font-bold text-gray-600">{{ from }} - {{ to }}</div>
    <h6 class="text-bold">{{ title }}</h6>
  </div>
</template>

<script>
import { Props } from "@/utils/props";

export default {
  props: {
    institute: Props.string(),
    location: Props.string(),
    from: Props.string(),
    to: Props.string(),
    title: Props.string()
  }
};
</script>

// components/Education.tsx
import React from "react";

interface Props {
  institute: string;
  location: string;
  from: string;
  to: string;
  title: string;
}

const Education: React.FC<Props> = ({
  institute,
  location,
  from,
  to,
  title
}) => {
  return (
    <div className="flex-1">
      <div className="font-semibold">{institute}</div>
      <div className="text-gray-700">{location}</div>
      <div className="font-semibold text-gray-700">
        {from} - {to}
      </div>
      <h6 className="font-semibold">{title}</h6>
    </div>
  );
};

export default Education;
