// src/components/Nav.svelte
<script>
  export let segment;
</script>

<nav class="app-navbar flex items-center justify-between flex-wrap p-4">
  <div class="flex items-center flex-shrink-0 mr-6">
    <a href="/">
      <div
        class="bg-blue-500 text-white text-xl font-semibold h-8 w-8 rounded-full
        flex items-center justify-center">
        <span class="pt-1">FB</span>
      </div>
    </a>
  </div>
  <div class="flex items-center flex-shrink-0">
    <div class="text-sm lg:flex-grow" />

    <a
      class="hover:text-blue-500 ml-4"
      href="/blog"
      rel="prefetch"
      class:text-blue-500={segment === 'blog'}>
      Blog
    </a>

    <a
      class="hover:text-blue-500 ml-4"
      href="/resume"
      rel="prefetch"
      class:text-blue-500={segment === 'resume'}>
      Resume
    </a>

  </div>
</nav>

// components/Nav.tsx
import React from "react";
import Link from "./Link";

const Nav: React.FC = () => {
  return (
    <nav className="app-navbar flex items-center justify-between flex-wrap p-4">
      <div className="flex items-center flex-shrink-0 mr-6">
        <Link href="/">
          <a>
            <div className="bg-blue-500 text-white text-xl font-semibold h-8 w-8 rounded-full flex items-center justify-center">
              <span>FB</span>
            </div>
          </a>
        </Link>
      </div>
      <div className="flex items-center flex-shrink-0">
        <Link href="/resume" activeClassName="text-blue-500 font-semibold">
          <a className="hover:text-blue-500 ml-4">Resume</a>
        </Link>
      </div>
    </nav>
  );
};

export default Nav;
