// src/components/Entry.svelte
<script>
  export let label = "";
  export let value = "";
  export let href = "";
</script>

<template>
  <div class="flex-1">
    <span class="font-bold">{label}</span>
    :
    {#if href}
      <a {href} target="_blank">{value}</a>
    {:else}
      <span>{value}</span>
    {/if}
  </div>
</template>

// components/resume/Entry.vue
<template>
  <div class="flex-1">
    <span class="font-bold">{{ label }}</span
    >:
    <a v-if="href" :href="href" target="_blank">{{ value }}</a>
    <span v-else>{{ value }}</span>
  </div>
</template>

<script>
import { Props } from "@/utils/props";

export default {
  props: {
    label: Props.string(),
    value: Props.string(),
    href: Props.string()
  }
};
</script>
