// components/Section.tsx
import React from "react";

interface Props {
  title?: string;
}

const Section: React.FC<Props> = ({ title, children }) => {
  return (
    <div className="section-container flex flex-col mx-4 py-4">
      {!!title && <div className="font-semibold text-3xl mb-4">{title}</div>}
      <div className="text-gray-800 flex flex-col justify-center">
        {children}
      </div>
    </div>
  );
};

export default Section;

// components/resume/Section.vue
<template>
  <div class="section-container">
    <div class="font-bold text-xl mb-2">{{ title }}</div>
    <div class="text-gray-700 flex flex-col justify-center text-sm">
      <slot />
    </div>
  </div>
</template>

<script>
import { Props } from "@/utils/props";

export default {
  props: {
    title: Props.string()
  }
};
</script>

<style lang="postcss">
.section-container {
  @apply flex flex-col mx-4;
}
.section-container:not(:last-child) {
  @apply mb-8;
}
</style>
