// pages/index.vue
<template>
  <div class="h-64 flex flex-col items-center justify-center m-4">
    <p class="text-4xl font-light">
      Hello, I am Fernando, and this is my website.
    </p>
    <p class="text-xl text-gray-600">
      I am a software developer, an UI engineer, a Webpack tuner.
    </p>
  </div>
</template>

// pages/index.tsx
import React from "react";
import TextLoop from "react-text-loop";

const Home: React.FC = () => (
  <div className="home flex flex-col md:justify-center m-4">
    <div>
      <div className="md:text-5xl text-2xl font-bold">
        Hello, I am Fernando.
      </div>
      <div className="md:text-5xl text-2xl">Welcome to my website!</div>
    </div>

    <div className="w-full md:text-5xl text-2xl mt-8">
      I am a{" "}
      <TextLoop interval={2000}>
        <span className="font-semibold">Software developer</span>
        <span className="font-semibold">UI Engineer</span>
        <span className="font-semibold">Webpack Tuner</span>
        <span className="font-semibold">PWA Passionate</span>
        <span className="font-semibold">Typescript Fan</span>
        <span className="font-semibold">Postgres Enthusiast</span>
      </TextLoop>{" "}
    </div>
  </div>
);

export default Home;
